# /config/packages/31_zaehler_haus_wp_strom.yaml
# Haus: Wärmepumpe & Allgemein – Verbrauch (kWh) und Kosten (€) inkl. Vormontage + Live-Preis

input_number:
  haus_wp_vormontage_kwh:
    name: "Haus – WP Strom: Vormontage [kWh]"
    min: 0
    max: 100000
    step: 0.1
    unit_of_measurement: "kWh"
    mode: box
  haus_wp_vormontage_preis_eur_kwh:
    name: "Haus – WP Strom: Vormontage Preis [€/kWh]"
    min: 0
    max: 5
    step: 0.001
    unit_of_measurement: "€/kWh"
    mode: box

  haus_allg_vormontage_kwh:
    name: "Haus – Allgemein Strom: Vormontage [kWh]"
    min: 0
    max: 100000
    step: 0.1
    unit_of_measurement: "kWh"
    mode: box
  haus_allg_vormontage_preis_eur_kwh:
    name: "Haus – Allgemein Strom: Vormontage Preis [€/kWh]"
    min: 0
    max: 5
    step: 0.001
    unit_of_measurement: "€/kWh"
    mode: box

template:
  - trigger:
      - platform: state
        entity_id:
          - sensor.zahler_xiao_c6_s0_kanal_1_leistung_w
          - sensor.zaehler_haus_allgemein_haus_s0_kanal_1_leistung_w
          - sensor.conny_strompreis
      - platform: time_pattern
        seconds: "/30"
    sensor:
      - name: "Haus – WP Kostenrate [€/h]"
        unique_id: haus_wp_kostenrate_eur_h
        unit_of_measurement: "€/h"
        icon: mdi:cash
        state: >-
          {% set p_w = states('sensor.zahler_xiao_c6_s0_kanal_1_leistung_w')|float(0) %}
          {% set price = states('sensor.conny_strompreis')|float(0) %}
          {{ ((p_w / 1000.0) * price) | round(6) }}

      - name: "Haus – Allgemein Kostenrate [€/h]"
        unique_id: haus_allg_kostenrate_eur_h
        unit_of_measurement: "€/h"
        icon: mdi:cash-multiple
        state: >-
          {% set p_w = states('sensor.zaehler_haus_allgemein_haus_s0_kanal_1_leistung_w')|float(0) %}
          {% set price = states('sensor.conny_strompreis')|float(0) %}
          {{ ((p_w / 1000.0) * price) | round(6) }}

  - sensor:
      - name: "Haus – WP Strom Verbrauch [kWh]"
        unique_id: haus_wp_strom_verbrauch_kwh
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: >-
          {{ ( states('sensor.haus_wp_strom_verbrauch_kwh_raw')|float(0)
             + states('input_number.haus_wp_vormontage_kwh')|float(0) ) | round(3) }}

      - name: "Haus – WP Strom Vormontage €"
        unique_id: haus_wp_strom_vormontage_eur
        device_class: monetary
        unit_of_measurement: "€"
        icon: mdi:cash
        state: >-
          {{ ( states('input_number.haus_wp_vormontage_kwh')|float(0)
             * states('input_number.haus_wp_vormontage_preis_eur_kwh')|float(0) ) | round(2) }}

      - name: "Haus – WP Strom Kosten gesamt €"
        unique_id: haus_wp_strom_kosten_gesamt_eur
        device_class: monetary
        unit_of_measurement: "€"
        icon: mdi:cash-multiple
        state: >-
          {{ ( states('sensor.haus_wp_kosten_eur_raw')|float(0)
             + states('sensor.haus_wp_strom_vormontage_eur')|float(0) ) | round(2) }}

      - name: "Haus – Allgemein Strom Verbrauch [kWh]"
        unique_id: haus_allg_strom_verbrauch_kwh
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: >-
          {{ ( states('sensor.haus_allg_strom_verbrauch_kwh_raw')|float(0)
             + states('input_number.haus_allg_vormontage_kwh')|float(0) ) | round(3) }}

      - name: "Haus – Allgemein Strom Vormontage €"
        unique_id: haus_allg_strom_vormontage_eur
        device_class: monetary
        unit_of_measurement: "€"
        icon: mdi:cash
        state: >-
          {{ ( states('input_number.haus_allg_vormontage_kwh')|float(0)
             * states('input_number.haus_allg_vormontage_preis_eur_kwh')|float(0) ) | round(2) }}

      - name: "Haus – Allgemein Strom Kosten gesamt €"
        unique_id: haus_allg_strom_kosten_gesamt_eur
        device_class: monetary
        unit_of_measurement: "€"
        icon: mdi:cash-multiple
        state: >-
          {{ ( states('sensor.haus_allg_kosten_eur_raw')|float(0)
             + states('sensor.haus_allg_strom_vormontage_eur')|float(0) ) | round(2) }}

sensor:
  - platform: integration
    source: sensor.zahler_xiao_c6_s0_kanal_1_leistung_w
    name: haus_wp_strom_verbrauch_kwh_raw
    unit_time: h
    unit_prefix: k
    method: trapezoidal
    round: 6

  - platform: integration
    source: sensor.zaehler_haus_allgemein_haus_s0_kanal_1_leistung_w
    name: haus_allg_strom_verbrauch_kwh_raw
    unit_time: h
    unit_prefix: k
    method: trapezoidal
    round: 6

  - platform: integration
    source: sensor.haus_wp_kostenrate_eur_h
    name: haus_wp_kosten_eur_raw
    unit_time: h
    unit_prefix: null
    method: trapezoidal
    round: 6

  - platform: integration
    source: sensor.haus_allg_kostenrate_eur_h
    name: haus_allg_kosten_eur_raw
    unit_time: h
    unit_prefix: null
    method: trapezoidal
    round: 6

utility_meter:
  haus_wp_kosten_tag:
    source: sensor.haus_wp_kosten_eur_raw
    cycle: daily
  haus_wp_kosten_monat:
    source: sensor.haus_wp_kosten_eur_raw
    cycle: monthly
  haus_wp_kosten_jahr:
    source: sensor.haus_wp_kosten_eur_raw
    cycle: yearly

  haus_allg_kosten_tag:
    source: sensor.haus_allg_kosten_eur_raw
    cycle: daily
  haus_allg_kosten_monat:
    source: sensor.haus_allg_kosten_eur_raw
    cycle: monthly
  haus_allg_kosten_jahr:
    source: sensor.haus_allg_kosten_eur_raw
    cycle: yearly

  haus_wp_verbrauch_tag_kwh:
    source: sensor.haus_wp_strom_verbrauch_kwh
    cycle: daily
  haus_wp_verbrauch_monat_kwh:
    source: sensor.haus_wp_strom_verbrauch_kwh
    cycle: monthly
  haus_wp_verbrauch_jahr_kwh:
    source: sensor.haus_wp_strom_verbrauch_kwh
    cycle: yearly

  haus_allg_verbrauch_tag_kwh:
    source: sensor.haus_allg_strom_verbrauch_kwh
    cycle: daily
  haus_allg_verbrauch_monat_kwh:
    source: sensor.haus_allg_strom_verbrauch_kwh
    cycle: monthly
  haus_allg_verbrauch_jahr_kwh:
    source: sensor.haus_allg_strom_verbrauch_kwh
    cycle: yearly
