# /config/packages/wp_kosten.yaml
# WP-Kosten: Rate = Leistung(kW) × Preis(€/kWh) + Summen (Stunde/Tag/Monat/Jahr)

# ───────────────────────────────────────────────────────────
# 1) Kostenrate [€/h] + Anzeige-Sensoren via Template
#    (ein gemeinsamer template:-Block, mehrere Listeneinträge)
# ───────────────────────────────────────────────────────────
template:
  - trigger:
      - platform: state
        entity_id:
          - sensor.zaehler_xiao_c6_s0_kanal_1_leistung_w
          - sensor.epex_spot_data_price
      - platform: time_pattern
        seconds: "/30"
    sensor:
      - name: "WP – Kostenrate [€/h]"
        unique_id: wp_kostenrate_eur_h
        unit_of_measurement: "€/h"
        state: >-
          {{
            (
              ( states('sensor.zaehler_xiao_c6_s0_kanal_1_leistung_w') | float(0) / 1000 )
              * ( states('sensor.epex_spot_data_price') | float(0) )
            ) | round(2)
          }}

  - sensor:
      # 2) Stundenkosten (€) aus kWh dieser Stunde × aktueller Preis
      - name: "WP – Kosten aktuelle Stunde [€]"
        unique_id: wp_kosten_stunde_eur
        unit_of_measurement: "€"
        device_class: monetary
        state: >-
          {{
            (
              states('sensor.wp_energy_hour') | float(0)
              * states('sensor.epex_spot_data_price') | float(0)
            ) | round(2)
          }}

  - sensor:
      # 3) Anzeige-Felder (€) für Tag / Monat / Jahr (gerundet)
      - name: "WP – Kosten Tag [€]"
        unique_id: wp_kosten_tag_eur
        unit_of_measurement: "€"
        device_class: monetary
        state: "{{ states('sensor.wp_kosten_tag_raw') | float(0) | round(2) }}"
      - name: "WP – Kosten Monat [€]"
        unique_id: wp_kosten_monat_eur
        unit_of_measurement: "€"
        device_class: monetary
        state: "{{ states('sensor.wp_kosten_monat_raw') | float(0) | round(2) }}"
      - name: "WP – Kosten Jahr [€]"
        unique_id: wp_kosten_jahr_eur
        unit_of_measurement: "€"
        device_class: monetary
        state: "{{ states('sensor.wp_kosten_jahr_raw') | float(0) | round(2) }}"

# ───────────────────────────────────────────────────────────
# 2) Utility-Meter – EIN Block für Stunde + €-RAW (Tag/Monat/Jahr)
# ───────────────────────────────────────────────────────────
utility_meter:
  # Stunden-kWh direkt vom Gesamtzähler
  wp_energy_hour:
    source: sensor.zaehler_xiao_c6_wp_zahlerstand_gesamt_kwh
    cycle: hourly

  # Kumulierte € (RAW) – werden unten per Integration erzeugt
  wp_kosten_tag_raw:
    source: sensor.wp_kosten_kumuliert_eur_raw
    cycle: daily
  wp_kosten_monat_raw:
    source: sensor.wp_kosten_kumuliert_eur_raw
    cycle: monthly
  wp_kosten_jahr_raw:
    source: sensor.wp_kosten_kumuliert_eur_raw
    cycle: yearly

# ───────────────────────────────────────────────────────────
# 3) Kumulierte €-Integration (aus Kostenrate [€/h])
# ───────────────────────────────────────────────────────────
sensor:
  - platform: integration
    source: sensor.wp_kostenrate_eur_h
    name: wp_kosten_kumuliert_eur_raw
    unit_time: h
    round: 6
